name: Build TTSApp Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build macOS app
        run: |
          pyinstaller --onefile --windowed --name TTSApp-macOS src/main.py

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: TTSApp-macOS
          path: dist/

  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows executable
        run: |
          pyinstaller --onefile --windowed --name TTSApp-windows src/main.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: TTSApp-windows
          path: dist/

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Linux executable
        run: |
          pyinstaller --onefile --windowed --name TTSApp-linux src/main.py

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: TTSApp-linux
          path: dist/
